### ISSUE TITLE
Support for 4 band png image

### ISSUE THREAD

**Issue by princealy** [canturan10/satellighte#20]
I have a satellite image with 4 bands. I get the following error: 

`AssertionError: channel size of the image must be 3 but found 4`

Is that something that can be supported. I attached an example image. 
![image](https://github.com/canturan10/satellighte/assets/108771219/ea3cf932-7cc1-41c2-989c-45096751820c)

**Comment by canturan10** [comment]
Hello There 👋

The error you're encountering (AssertionError: channel size of the image must be 3 but found 4) suggests that the software or library expects input images with three channels (RGB), but your satellite image has four bands.

You can remove the alpha channel from your image using the following code:
``` python
img_rgb = Image.fromarray(img[:, :, :3])
```

This code creates a new image (img_rgb) from your original image (img) by selecting only the first three channels, effectively removing the alpha channel.

If you encounter any further issues or need additional assistance, please let us know.

**Comment by princealy** [comment]
Thanks a lot! That fixed the issue
